/*
 * Auto-generated by Frida. Please modify to match the signature of -[HuntWord init].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

Interceptor.replace(Module.getExportByName(null, "exit"),
  new NativeCallback(function (code) {
    console.log("• exit(" + code + ") called - ignoring");
  }, 'void', ['int']));

defineHandler({
  onEnter(log, args, state) {
    log(`-[HuntWord init]`);
  },

  onLeave(log, retval, state) {
  }
});
